name: moral-agent
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - flake8
  - flake8-docstrings
  - pytest
  - jupyter
  - tqdm
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - numba
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - tensorboard
